# Generated by Django 3.2.3 on 2021-07-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_auto_20210704_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'verbose_name_plural': 'Donate'},
        ),
    ]
